lva_events_homepage:
    path:     /
    defaults: { _controller: LVAEventsBundle:Default:index }
events_homepage:
    path:     /events
    defaults: { _controller: LVAEventsBundle:Event:index }
events_add:
    path:     /events/add
    defaults: { _controller: LVAEventsBundle:Event:add }
    
category_homepage:
    path:     /category
    defaults: { _controller: LVAEventsBundle:Categorie:index }
    
add_category:
    path:     /category/add
    defaults: { _controller: LVAEventsBundle:Categorie:add }
    
univer_homepage:
    path:     /univers
    defaults: { _controller: LVAEventsBundle:Univer:index }
    
theme_homepage:
    path:     /themes
    defaults: { _controller: LVAEventsBundle:Theme:index }
add_theme:
    path:     /themes/add
    defaults: { _controller: LVAEventsBundle:Theme:add }
